name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */2 * * *" # Run every 2 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -s "https://roth401-or-self-invest.streamlit.app/?user_id=9be41e85-1720-43d4-bae1-ce1d3522fc24"
          echo "Ping completed at $(date)"
